### ISSUE TITLE
Document End to End Scenario for OSIO

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#11]
References:
Burr's Hello World Videos (ref: https://docs.google.com/document/d/1OszzoSyv2gqv8mlSg1yHeBxMAk9v4rGCKg_FkfN_d7w/edit#heading=h.a5lc9uymo7qx)
Steps:
https://docs.google.com/spreadsheets/d/1B2ckTXCsKc8sD_S2p7OP7d1fvcMI8_6tjTosT3ihSMM/edit#gid=547154663

**Comment by rkratky** [comment]
Main workshop document: https://docs.google.com/document/d/1KsV8oHRe7DYCVCMfVrB2yd3hU4iBi11YI5MyuXoozQw/ (Burr: "it's the workshop bible, and everyone needs to read it").

**Comment by mishaone** [comment]
Finished the first version of this a while ago so I'm closing this off. Doc is currently available at internal preview link.
