### ISSUE TITLE
Document Space name limitations

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#115]
Monitor https://github.com/openshiftio/openshift.io/issues/676 and document its results when it gets resolved.

**Comment by mishaone** [comment]
Asked for clarification about requirements. No response yet. Check back later.

**Comment by Preeticp** [comment]
Just saw tentative designs for new UX, I believe the UX for this would be self explanatory, afaiu docs may not be needed, we will need to add at least one screenshot for space creation and app creation, both of which capture the requirements on the screen itself.

**Comment by Preeticp** [comment]
The new design puts these restrictions right upfront on the UX and docs would have screenshots, hence there is no requirement to add it to the docs. Closing this post confirmation from Joshua.
