### ISSUE TITLE
Propose better structure for e2e doc

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#118]
Created this issue to propose improvements to the ToC for the E2E doc. This seems like the sort of thing we can discuss and agree upon beforehand so that it's easy to implement and test in one go.

**Comment by mishaone** [comment]
*Current ToC:*

Part 1: Before you start

Ch 1. Introduction
   - Early access program
   - Providing feedback
   - Resetting your environment

Ch 2. About this document
   - Getting support
   - Product questions
   - Providing product feedback
   - Providing documentation feedback

Ch 4. Prerequisites

Ch 5. Connecting OpenShift.io to OpenShift Online and GitHub

Ch 6. Confirm Che and Jenkins status

Part 2: Start using OpenShift.io

Ch 7. Hello World for Developers
   - Creating a new space
   - Creating a new project
   - About the stage and run environments
   - Working with pipelines
   - Viewing the build pipeline in OpenShift Online
   - About codebases
   - Approving the build pipeline
   - (Optional) detailed views
   - Creating and using a new work item
   - About workspaces
   - Creating a Che workspace
   - Prerequisites for using your Che workspace
   - Changing the quickstart code
   - Commit and push changes to GitHub
   - Review and publish your changes
   - Closing a work item

Ch 8. Optimizing your memory usage
   - Reviewing the resource information in OpenShift Online
   - Monitor your OpenShift Online quota usage
   - Reduce the Hello World project memory usage
   - Commit and push changes to GitHub

Ch 9. Analyzing the application
   - Analyzing Che dependencies
   - Using stack reports
   - Viewing your project in GitHub
   - Viewing projects in OpenShift Online
   - Using advanced Che features
   - Using the code assistant
   - Using the terminal tab
   - Debugging your Che workspace
   - Set up the debugger
   - Run the debug command

Ch 11. Spring Boot Quickstart Tutorial
   - Creating a new project
   - Stopping existing workspaces
   - Creating a Che workspace
   - Using a workspace for the Spring Boot project
   - Reduce Spring Boot project memory usage
   - Commit and push changes to GitHub

Ch 12. Cleaning up your OpenShift Online Account

Ch 13. Importing an existing project from GitHub
   - Forking a Repository
   - Creating a new space
   - Import your project
   - Creating a Che workspace
   - Prerequisites for using your Che workspace
   - Changing the project code
   - Commit and push changes to GitHub
   - Review and publish your changes
   - Next steps

**Comment by Preeticp** [comment]
+1 makes sense

**Comment by mishaone** [comment]
Where would you suggest putting Resetting your environment? I put it up front since this is, realistically speaking, something users will need to know about generally (i.e. if you're in stuck and can't fix the problem, resetting the environment is the last resort).

**Comment by rkratky** [comment]
My thinking was to leave out of the intro chapter completely since it has its own chapter in "Cleaning up your OpenShift Online Account". If you think we need to have it up front, then perhaps at the end of "Getting support"?
