### ISSUE TITLE
Streamline and document workflow for Adding and Importing codebases.

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#121]
Derivative of #114

**Comment by mishaone** [comment]
Are you working on this, @Preeticp? I'm looking through unowned issues to find things nobody has taken on.

**Comment by Preeticp** [comment]
@mishaone I am currently working on the Planner and Analytics sections of the User guide. If you have the bandwidth, please feel free to take it up. If not, I will get onto this as soon as I am done with the other two.

**Comment by Preeticp** [comment]
@mishaone this work would probably be influenced by #192 as well.

**Comment by Preeticp** [comment]
Closing this issue as the changes through #192 would greatly affect this section and can be tracked through that issue itself.
