### ISSUE TITLE
Final decision wrt caps

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#124]
This debate petered out. Let's decide on and start following some rules: Based on previous discussions, I propose:

- capitalize only when featured as a label of a GUI element: "click Space to open a new space"
- capitalize only first word: "click Work item to open a new work item"
- file issue against app UI where inconsistent with the above

Thoughts?

**Comment by mishaone** [comment]
I'd propose that for GUI labels we go with whatever is actually on the GUI. If it's wrong (as in the case of "organisation" for example in the Quickstart menu), we should document it as it is and log an issue to fix it, then fix it in the docs to reflect the change in GUI. My reasoning for this that it should be exactly as the user will see it in the product, even if wrong or inconsistent, to be useful in terms of instructions.

Additionally, we should be marking up GUI label so they should already stand out from the rest of the sentence. Example (not necessarily this markup, but whatever is recommended in the conventions): Click *Work item* to create a work item.

That's my two cents on GUI elements. I think a tricker discussion was around terms specific to the product, such as Collaboration Space/Space, Iterations, Work Items, etc.

**Comment by rkratky** [comment]
> I'd propose that for GUI labels we go with whatever is actually on the GUI. If it's wrong (as in the case of "organisation" for example in the Quickstart menu), we should document it as it is and log an issue to fix it, then fix it in the docs to reflect the change in GUI. My reasoning for this that it should be exactly as the user will see it in the product, even if wrong or inconsistent, to be useful in terms of instructions.

+1 That's what I meant but formulated lazily.

> Additionally, we should be marking up GUI label so they should already stand out from the rest of the sentence. Example (not necessarily this markup, but whatever is recommended in the conventions): Click Work item to create a work item.

+1 The conventions call for bold, i.e. `*Work item*`.

> I think a tricker discussion was around terms specific to the product, such as Collaboration Space/Space, Iterations, Work Items, etc.

I vote for following the same rules as with the rest. I.e. `click the *Iteration* menu item to create an iteration` or `click btn:[Iteration] to create an iteration` (depending on the UI).

**Comment by Preeticp** [comment]
I am glad we are coming to some agreement on this.

> click the *Iteration* menu item to create an iteration or click btn:[Iteration] to create an iteration (depending on the UI).

+1, I am for this.

So based on the above discussion, this:
> "click Work item to open a new work item"  
would be "Click **Work item**/**Work Item**(depending on the UI) to open a new work item".

**Comment by rkratky** [comment]
> would be "Click Work item/Work Item(depending on the UI) to open a new work item".

Yes, but if the UI shows "Work Item", an issue should be filed against it.

**Comment by mishaone** [comment]
Sounds like we're in agreement on this. Shall we close this issue?

**Comment by rkratky** [comment]
Cool. Thanks Misha, Preeti.
