### ISSUE TITLE
Track changes in /getting-started page

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#150]
The UX team is planning to remove the `/getting-started` page. The Getting Started Guide (and possibly the User, Guide, too) need to be checked and potentially updated to reflect this change when it happens.

**Comment by mishaone** [comment]
I'll take this one and check it periodically for changes.

**Comment by rkratky** [comment]
@mishaone This is now in prod-preview. Please, update the docs.

**Comment by mishaone** [comment]
Removed content and created PR: https://github.com/fabric8io/fabric8-online-docs/pull/213

**Comment by mishaone** [comment]
Another PR addressing the GitHub part: https://github.com/fabric8io/fabric8-online-docs/pull/216

**Comment by rkratky** [comment]
@mishaone Is there anything still to do for this issue?

**Comment by mishaone** [comment]
Nope, sorry, I meant to close this when I closed the other one in the OSIO repo, but got distracted. Closing now.
