### ISSUE TITLE
Review screenshots and add them (chapter by chapter)

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#153]
Using this issue to track which chapters we're working on for screenshots. please feel free to edit and assign yourself to a chapter you're working on so we don't double up.

* ch 1 - misha done
* ch 2 - misha done
* ch 3 - misha done
* ch 4 - misha WIP
* ch 5 - 
* ch 6 - 
* ch 7 - 
* ch 8 - 
* ch 9 - 
* ch 10 - preeti WIP

**Comment by Preeticp** [comment]
As in the other issue, will begin from the other end with chapter 10, Importing project.

**Comment by mishaone** [comment]
@Preeticp please update if you move past the current chapter you're on so we don't duplicate the work (same for the other issue)

**Comment by Preeticp** [comment]
Sure @mishaone, was working on other Planner and Analytics issues which had to go in asap.

**Comment by rkratky** [comment]
@mishaone I see you marked the first 3 chapters as done. Please, submit a PR (or PRs) for those, so that we can a) continuously update the prod doc, and b) work on other stuff in those chapters without running a risk of conflicts.

**Comment by mishaone** [comment]
For the sake of tracking this issue, this is the first PR: https://github.com/fabric8io/fabric8-online-docs/pull/163

**Comment by mishaone** [comment]
PR #2: https://github.com/fabric8io/fabric8-online-docs/pull/165

**Comment by mishaone** [comment]
PR3: https://github.com/fabric8io/fabric8-online-docs/pull/167

**Comment by mishaone** [comment]
PR4: https://github.com/fabric8io/fabric8-online-docs/pull/168

**Comment by mishaone** [comment]
PR5: https://github.com/fabric8io/fabric8-online-docs/pull/169

**Comment by mishaone** [comment]
PR7: https://github.com/fabric8io/fabric8-online-docs/pull/172
(6 was just one screenshot)

**Comment by mishaone** [comment]
Pr8: https://www.youtube.com/watch?v=E7ZTh9Rd0aA&sns=tw

**Comment by mishaone** [comment]
PR9: https://github.com/fabric8io/fabric8-online-docs/pull/177

**Comment by mishaone** [comment]
This task is done, except the SpringBoot quickstart part, which is commented out. This will be updated later when Todd & co decide what they want to replace that part of the tutorial. Closing this as done (and pushed to production).
