### ISSUE TITLE
update the "distracting" file name for the main GS page

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#154]
Todd commented that he found the e2e_workshop.html file name distracting in the URL.

I suggest we change this to something like osio_gettingstarted.html or just gettingstarted.html. Thoughts, @rkratky and @Preeticp? This seems like an easy fix we can make based on Todd's feedback. Assigning to Robert since this may need changing in a couple of places aside from the assembly doc for the scripts to work.

**Comment by rkratky** [comment]
Oops, apologies, I haven't noticed this issue, so I opened #158 for the same. It's now fixed by #159.
