### ISSUE TITLE
Review language and add more enthusiasm, excitement, etc. for GS doc

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#155]
Using this issue to track which chapters we're working on for making the language more "fun, enthusiastic, etc". please feel free to edit and assign yourself to a chapter you're working on so we don't double up. This excludes the introduction, which I'll track separately.

* ch 1 - misha - done
* ch 2 - misha - done
* ch 3 - misha - done
* ch 4 - misha - WIP
* ch 5 - 
* ch 6 - 
* ch 7 - 
* ch 8 - 
* ch 9 - 
* ch 10 - preeti WIP

**Comment by Preeticp** [comment]
I will start from the other end with chapter 10, Importing a project. Please note, lot of the modules in it are common to chapter 4.

**Comment by mishaone** [comment]
All good, @Preeticp. For the sake of organization, I've referred to our GS doc's chapters here, which may correspond to different chapters/sections in Todd's GS doc.

**Comment by mishaone** [comment]
For the sake of tracking work done for this, this is the first PR: https://github.com/fabric8io/fabric8-online-docs/pull/163

**Comment by mishaone** [comment]
PR#2: https://github.com/fabric8io/fabric8-online-docs/pull/165

**Comment by mishaone** [comment]
PR3: https://github.com/fabric8io/fabric8-online-docs/pull/167

**Comment by mishaone** [comment]
PR4: https://github.com/fabric8io/fabric8-online-docs/pull/168

**Comment by mishaone** [comment]
PR5: https://github.com/fabric8io/fabric8-online-docs/pull/169

**Comment by mishaone** [comment]
PR7: https://github.com/fabric8io/fabric8-online-docs/pull/172
(6 was just one screenshot)

**Comment by mishaone** [comment]
PR8: https://www.youtube.com/watch?v=E7ZTh9Rd0aA&sns=tw

**Comment by mishaone** [comment]
PR9: https://github.com/fabric8io/fabric8-online-docs/pull/177

**Comment by mishaone** [comment]
This task is done, except the SpringBoot quickstart part, which is commented out. This will be updated later when Todd & co decide what they want to replace that part of the tutorial. Closing this as done (and pushed to production).
