### ISSUE TITLE
s/intro/todd's intro + review

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#156]
As discussed, I'm going to leave our intro and create a separate module to include Todd's intro so that we have more enthusiasm, fun, etc. for the user. This task includes reviewing and making the language a bit more professional.

**Comment by mishaone** [comment]
Created PR: https://github.com/fabric8io/fabric8-online-docs/pull/157

Asked Robert to review and merge if ok.

**Comment by rkratky** [comment]
Fixed by #157
