### ISSUE TITLE
Typo in Intro chapter

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#164]
1. Introduction

"A more important aspect of the Early **Aspect** Program is to get your feedback."

**Comment by mishaone** [comment]
Fixed as part of larger PR. Link when I create PR.

**Comment by mishaone** [comment]
Included in this PR: https://github.com/fabric8io/fabric8-online-docs/pull/165

**Comment by mishaone** [comment]
PR is merged. Closing issue.
