### ISSUE TITLE
Update docs when 'Applications' and 'Environments' screens go away

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#173]
Todd: _"The Application and Environments screens are going away, being replaced by a single Deployments screen. You can set your profile feature level down to "Internal" to see the Deployments screen."_

**Comment by Preeticp** [comment]
Joshua: we need the getting started doc updated, we have removed the App and Env pages in prod-preview

**Comment by joshuawilson** [comment]
Do we have a time line on when this can be updated?

**Comment by mishaone** [comment]
Work in progress on this now.

**Comment by mishaone** [comment]
Initial PR (doesn't include a lot of env and app changes since this was rolled back): https://github.com/fabric8io/fabric8-online-docs/pull/178

More changes to come once the updates are back in prod-preview.

**Comment by mishaone** [comment]
Second PR: https://github.com/fabric8io/fabric8-online-docs/pull/179

Validated, tested and looks okay. Ready to be shared publicly whenever the team is ready.

**Comment by joshuawilson** [comment]
Thanks @mishaone

**Comment by rkratky** [comment]
@mishaone Apologies for the delay. Just merged to prod.

**Comment by joshuawilson** [comment]
@rkratky I noticed that the `Deployments` page image is with the `internal` setting, it is `experimental` in production. @corinnekrych can you please update prod-preview accordingly.

**Comment by mishaone** [comment]
@joshuawilson I'll review and update as soon as this is available in prod-preview.

**Comment by joshuawilson** [comment]
@mishaone the same link (https://fabric8-ui-fabric8-ui-pr-2516-fabric8-ui.badger.fabric8.io/) will continue to work until the PR is merged. And feature toggle has been updated.

**Comment by mishaone** [comment]
@joshuawilson I'm blocked on some parts of the documentation (currently using some hacky workarounds or omitting altogether) based on this issue: https://github.com/openshiftio/openshift.io/issues/945 (last comment is my current situation with the PR build/prod-preview).

**Comment by joshuawilson** [comment]
OK, I understand. We can take two approaches on this. The docs are updated even if they need a new image. So I can make the changes in prod, but I need to get these new docs linked in the app. If the issue you are facing with the pipelines gets fixed first then you can get your image. If we get the links updated and the change pushed then you can get it from prod. Either way we will have it sorted out in the next few days.

**Comment by mishaone** [comment]
Sounds good either way, Joshua. Thanks and I'll keep trying for now until the situation is resolved in the next few days.

**Comment by mishaone** [comment]
Hi @joshuawilson - any update on this situation?

**Comment by joshuawilson** [comment]
@mishaone can you try https://fabric8-ui-fabric8-ui-pr-2516-fabric8-ui.badger.fabric8.io/ for the updated version with the updated feature flag.

**Comment by mishaone** [comment]
Sorry, @joshuawilson, same issue. 
![nojoy](https://user-images.githubusercontent.com/926572/36293190-3738d324-1323-11e8-9860-821a008f8123.png)

I can get the workflow working on production, and sbose examined my network log and said it was just the issue I mentioned before where builds either take ages or don't start at all.

**Comment by joshuawilson** [comment]
have you tried updating your tenant?

**Comment by mishaone** [comment]
I have. It just seems to be an issue with the prod-preview and PR builds, but seems to work relatively reliably on production.

**Comment by joshuawilson** [comment]
ah, I think you need to update your account to use free-stg on prod-preview

**Comment by mishaone** [comment]
This should be done and now pushed to prod as well here: https://docs.openshift.io/getting-started-guide.html#optional_detailed_views

@joshuawilson, could you have a look and confirm you're satisfied and we can close this issue?

**Comment by joshuawilson** [comment]
looks good to me
