### ISSUE TITLE
GS doc feedback

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#174]
Feedback on Todd's doc, to be checked in the latest version of our GS doc:

* P17, “Name” is in the docs, “OpenShift Project Name” is in GUI.
* P26: Instruction to click “Create workspace” actually missing.
* P27: It is not obvious where the command-line screenshot comes from. My Che instance didn’t show any of that.
* P37: Does not say whether the reader should commit the changes.
* P38: Missing information about what to do with Stack report.
* P46, par. 3: It’s not a red X that appears, but a yellow triangle. Also, gutter seems quite a specialized term to me to be used in a Getting Started material.
* P47, par. 1: Tell users it is the Terminal window on the bottom of Che, not just any terminal.
* P49, par. 2: Not obvious how the reader should save (commit? push?) or what hot redeploy is.
* P50, par. 1: It’s not obvious where the stop button is without the screenshot (bad for accessibility).
* P51, par 1: Not obvious which of the plusses to press without the screenshot (bad for accessibility).
* P51: Could provide information that double-clicking the line number creates a bookmark and not a breakpoint.

Excluding screenshots feedback since we are updating all screenshots on an ongoing basis anyway.

I'm tentatively assigning this to myself, but anyone else can take this if they have the time before I do.

**Comment by Preeticp** [comment]
@mishaone, I have done a review of the getting started guide wrt this issue before I went for PTO, the PR was merged by Rkratky. If you notice any more required changes, let me know. I can take care of it once I'm back from PTO, next week.

**Comment by mishaone** [comment]
Hey @preeti. No problem. If you already took care of it, I'll set this to you and close it. :)
