### ISSUE TITLE
Document create work item features more comprehensively in GS doc

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#181]
Reference from issue Rick logged here: https://github.com/openshiftio/openshift.io/issues/1755

Check our GS doc to ensure the documentation for the create work item feature is as complete as it needs to be for the workflow.

**Comment by mishaone** [comment]
We now have a "creating and using new work item" section in the GS doc that should address this issue: https://docs.openshift.io/getting-started-guide.html#creating_using_new_work_item

**Comment by Preeticp** [comment]
@mishaone the Getting Started Guide covers only part of the work item flow. openshiftio/openshift.io#1755 imho talks about other features of the Work Item which would be covered in the User Guide. This work is currently in progress, completed section has been shared with the dev team for further inputs. Request to keep this issue open till we have those sections in too.

**Comment by mishaone** [comment]
@Preeticp - I'm not sure the GS should have a comprehensive coverage of any feature aside from what is required for the workflow being described. Perhaps a separate issue for the UG to cover work items comprehensively would be more accurate? I can't really argue for having that kind of coverage in the GS doc because that's not the purpose of the doc, while the UG definitely fits that purpose. WDYT?

**Comment by Preeticp** [comment]
@mishaone, separate issue for UG makes sense. I agree, we do not want to cover detailed information in the GS doc. I just thought we could use the same issue for tracking that work too as it is related to the same OSIO parent issue and since UG work is in progress too. Will close this and open a new one.
