### ISSUE TITLE
Document integration of "Getting Started ngx-forge/ngx-launcher in Openshift.io"

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#192]
Add docs to both GSG (example of use) and UG (feature description) when feature/flow implemented. See https://github.com/openshiftio/openshift.io/issues/2178 for details.

**Comment by Preeticp** [comment]
@rkratky I am keeping a watch on this.

**Comment by Preeticp** [comment]
Have got hold of invision docs for this from UX, so there are 2 parts to this, one is the launcher part and the other is the dependency editor(DE) part. The DE part is ready, the Launcher part, still evolving. What needs figuring still is, how the DE fits into the Launcher Getting Started experience.
Scheduled a session with one of the devs to get more information on the overall picture. @rkratky let me know if there is anything else I am missing.

**Comment by rkratky** [comment]
@Preeticp Thank for following up on this. Please, keep updating this issue with info as you get it.

**Comment by Preeticp** [comment]
Currently, the Launcher experience can be seen in the prod-preview (In your space>Add to space>new import experience). 
While work flow is likely to remain similar, discussion is ongoing on a lot of pieces, current UX is common to both Launcher and OSIO. Certain part of the experience will be relevant only to OSIO, so pieces would be removed or modified accordingly. A lot of the experience is similar to the earlier wizard but presented in a much more user friendly way and there is a lot of explanation and text on the UX itself, making it pretty self explanatory. 
DE most likely to fit in between first two steps of launcher. Overall idea is when a user selects his stack, it will be analyzed and recommendations for alternate/additional dependencies will be provided, then itself but I am still to examine the DE piece. All this is based on the over view provided by the Dev.

**Comment by Preeticp** [comment]
https://github.com/openshiftio/openshift.io/issues/2440
https://github.com/openshiftio/openshift.io/issues/2217
Adding these issues here to allow easy tracking for this work.

**Comment by Preeticp** [comment]
As per stand up discussion today, DE would be an optional feature in the overall launcher flow. That is, based on the user profile, an user can opt in or out of this feature. If he opts in he will see the DE in the launcher work flow, if not then it will not be part of the work flow.

**Comment by rkratky** [comment]
This is too broad. Closing and splitting it up to:

- Document Launcher interface and features in the UG: #231
- Document Dependency Editor interface and features in the UG: #232
- Adapt existing Vert.x GSG story to use Launcher: #233
- Adapt existing Spring Boot GSG story to use Launcher: #234
