### ISSUE TITLE
Document the why of SDD

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#196]
First draft has been created, partial review comments received. Awaiting recording as further inputs for the concept topics.
https://docs.google.com/document/d/1BY3Ro82v3fsTkEv96VcuCF-meJmT81dDmV_yhmTLVkE/edit?usp=sharing

**Comment by Preeticp** [comment]
Workflow has already been covered in the creating, modifying WI sections.

**Comment by rkratky** [comment]
@Preeticp I understand the concepts have already been documented. Perhaps we should change the title and description of this issue to make it only about the 'why'?

**Comment by Preeticp** [comment]
+1 changed the title. Received review comments for the concepts will be pushing it to the glossary asap.
