### ISSUE TITLE
New repo structure

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#198]
Proposed new structure:

```
docs
├── images
│   ├── image1.png
│   └── image2.png
├── styles
│   └── styles.css
└── topics
    ├── assembly1.adoc
    ├── assembly2.adoc
    ├── guide1.adoc
    ├── guide2.adoc
    └── modules
        ├── module1.adoc
        └── module2.adoc
```

**Comment by mishaone** [comment]
My suggestion illustrated:

docs
├── images
│   ├── image1.png
│   └── image2.png
├── styles
│   └── styles.css
├── assembly1.adoc
├── assembly2.adoc
├── guide1.adoc
├── guide2.adoc
└── modules
     ├── module1.adoc
     └── module2.adoc
