### ISSUE TITLE
Jenkins idling issue - document or not?

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#212]
I've seen this as well. The tenant status for Jenkins stays on grey (waiting) for a very long time unless we go to jenkins.openshift.io, where we see idling status and eventually Jenkins becomes ready to start. If we create quickstarts, etc. while Jenkins is idling, the pipeline builds get stuck forever on the first start. Checking if it's worth adding to docs or if this will be fixed.

**Comment by mishaone** [comment]
Update: This is a design decision and may be changed in the future but for now, documentation is probably best.

**Comment by rkratky** [comment]
> This is a design decision

Is there any reasoning behind that? In other words, can we offer a reasonable (logical) workaround in docs, or is it on the level of a known issue?

**Comment by mishaone** [comment]
The idea is that Jenkins is meant to be idling when it's not in use but the user may still be using OSIO. For example, using the Planner. At the moment, there appears to be an odd issue where Jenkins does not stop idling until the user visits a separate page (jenkins.openshift.io) and waits for the idling process to conclude. Therefore, the idling when not in use is by design, but the not coming out of idle state when someone does something relevant in OSIO isn't and will be fixed. As a troubleshooting item (since I've encountered this a fair bit myself), I think it's useful to tell users in the docs to go to that link to nudge Jenkins out of idle state if they are stuck rather than wait forever or have builds fail.

**Comment by Preeticp** [comment]
Based on discussions with the Dev (Deploy team) this is not an issue anymore and was resolved sometime back. Also going to jenkins.openshift.io and waiting there is the same as waiting on the Pipelines page, there is nothing further that the user can do after going to the page to move Jenkins out of the idle state.  Closing this.
