### ISSUE TITLE
document troubleshooting - when to use update tenant/reset env

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#222]
I'm trying to fit these two buttons into the user story.
* When should the user use `Reset environment`?
* When should the user use `Update tenant`?
* Do we need to use both when clearing out OSIO?
* What to do if the tenant status indicator shows that Jenkins is not working. E.g:
![jenkins](https://user-images.githubusercontent.com/926572/37751921-eae3e788-2de0-11e8-99a6-1765303d4d0b.png)

**Comment by mishaone** [comment]
So far, information from sbose:

```If you Reset Environment, you don't need Update Tenant separately - 'update tenant' is a subset of 'reset environment'.

Reset Environment helps dealing with overflowing quota usages, and sometimes with getting artifact changes which aren't part of 'openshift object updates' aka tenant version updates. 

If Jenkins is not working, best ask the user to check 'Events' for the Jenkins deployment in the -jenkins namespace. Or, for a more clean slate strategy, "reset environment".``

**Comment by mishaone** [comment]
Removing status indicator: https://github.com/fabric8io/fabric8-online-docs/issues/274

Question now is how to tell when tenant is ready? Do we need to tell?

**Comment by rkratky** [comment]
@mishaone From what Catherine said, I understand everyone acknowledges that it would be useful to have the status info available, but given the fact the indicator doesn't work, we might as well do away with it (at least for the time being).

**Comment by Preeticp** [comment]
> When should the user use Reset environment? 

This is well documented in the GS
> When should the user use Update tenant?

This is something I am following up with Platform devs, once we get the info as to what the Update tenant on UX currently does, we might need to check with Joshua if this needs to be documented. Based on discussions here: https://github.com/openshiftio/openshift.io/issues/2307 they were talking about removing it. 
> Do we need to use both when clearing out OSIO?

No
> What to do if the tenant status indicator shows that Jenkins is not working. E.g:

This has been removed, see: https://github.com/openshiftio/openshift.io/issues/2678 for discussion.

**Comment by Preeticp** [comment]
> When should the user use Update tenant?
As per the devs, 'update tenant' is a subset of 'reset environment', whenever you reset your environment your tenants are automatically updated. Also as tenants get updated, user's tenants are automatically updated so the end user, most often, does not need to use this. As such this does not seem to warrant any docs. Closing this issue as all the questions seem to be answered.
