### ISSUE TITLE
Invalid infotips JSON

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#230]
@debloper:

* objects are to be separated by commas
* all the objects should ideally be contained in an array

**Comment by rkratky** [comment]
@debloper, please, have a look at the JSON file now and let me know if it's what you expect: https://docs.prod-preview.openshift.io/json/infotips.json

**Comment by debloper** [comment]
One thing to mention here (which of course doesn't affect anything from frontend's perspective) but I'm unsure if `en_EN` is needed to be generic English language `code_SUB`.

For generic language code, it's best to leave them to their ISO 639-1 codes (so, just `en` for English, if the sub-code isn't required). There's also no `EN` sub-code by ISO 3166-2 spec, so it looks like a spaceholder (for xx_YY code/naming consistency), which breaks the standard spec.
