### ISSUE TITLE
Document Launcher interface and features in the UG

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#231]
- see #192 for context
- consider reuse of Launcher docs from https://appdev.openshift.io/docs/getting-started.html

**Comment by Preeticp** [comment]
I can take this up.

**Comment by Preeticp** [comment]
Quick Start demo
https://drive.google.com/file/d/1y8DJd-6ncBRwAcrVv0_2r-YVrsr1Waab/view
Import Demo
https://drive.google.com/file/d/1_MIhvxpukRkLQQLVWT0h47cW25R_MXuG/view

**Comment by Preeticp** [comment]
Please note Launcher flow would now be the default flow if we enable experimental feature, more details here: https://github.com/openshiftio/openshift.io/issues/3285

**Comment by Preeticp** [comment]
WIP

**Comment by Preeticp** [comment]
fixed via #320
