### ISSUE TITLE
Document Dependency Editor interface and features in the UG

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#232]
see #192 for context

**Comment by Preeticp** [comment]
I can take this up.

**Comment by Preeticp** [comment]
Related to this dev issue: https://github.com/openshiftio/openshift.io/issues/2810

**Comment by Preeticp** [comment]
Have been asked to hold work on this till there is a firm go ahead from the Dev team, as they are not sure if this would be ready for GA. Would probably get more clarity on this by next week.

**Comment by Preeticp** [comment]
Note: #2810 requires me to work on the content on the UX as well as document it in the guides.

**Comment by Preeticp** [comment]
Removing this issue from GA milestone, this will not be part of internal features for GA. However the Dev team will be creating a video for the summit hence need to create UX content for them by today eod. Working on that now.

**Comment by Preeticp** [comment]
Added to prod-preview this week, saw a demo, currently being stabilized and ironed out, will paste link once they are shared.

**Comment by Preeticp** [comment]
This is in prod as an internal feature now, meeting scheduled today/monday to discuss the UX issues I highlighted in the current version. 
Question is do we document this even if it is Internal or do we document only Prod-Beta level features? Will be checking this with the Dev too, but @rkratky and @mishaone are we good to follow this understanding?
Mostly we would be able to take this up in Iteration 151 only, post confirmation in the dev meeting today will slot it in the next iteration and take up something else from the backlog instead.

**Comment by Preeticp** [comment]
This is still an internal feature, undergoing modifications based on feedback from Dev. Likely to continue and progress to Experimental in the coming sprint and then move to Beta. Currently ask is for UX content, docs can wait till Beta.

**Comment by Preeticp** [comment]
Continues to stay experimental and on hold till further notice. Removing from the milestone.

**Comment by Preeticp** [comment]
This work has been shelved for the moment by the developer team. Closing this issue post discussion with team. Will reopen when it is taken up again.
