### ISSUE TITLE
Remove/comment out references to board view in Planner

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#238]
Reference:
Dev issue:
https://openshift.io/openshiftio/openshiftio/plan/detail/1945?q=(space:020f756e-b51a-4b43-b113-45cec16b9ce9%20$AND%20$WITGROUP:Scenarios)
For GA, Board view will not be in the UX or will be part of internal/experimental features. Discussions are ongoing. Meanwhile we have been asked to remove/comment out references to the board view.
This affects both the guides and influences #235

**Comment by mishaone** [comment]
Happy to take this on, but probably when it's actually available in the UI so I can see what to switch out the references with.

**Comment by rkratky** [comment]
@Preeticp Any ETA on when this will hit prod-preview?

**Comment by mishaone** [comment]
Nevermind, didn't actually need a change yet, assuming the board button just disappears from the UI.

Created PR: https://github.com/fabric8io/fabric8-online-docs/pull/254

**Comment by mishaone** [comment]
Also deleted a module and some images (after confirming they are not used elsewhere in the docs) since they pertain to just board view and therefore are no longer needed.

**Comment by rkratky** [comment]
@mishaone #254 has been merged. Can we close this?
