### ISSUE TITLE
Add guidelines for branch naming

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#249]
Update the CONTRIBUTING file with the following:

* i1234-f8-fixing-blah (issues raised in https://github.com/fabric8io/fabric8-online-docs/issues)
* i1234-io-fixing-blah (issues raised in https://github.com/openshiftio/openshift.io/issues)

**Comment by mishaone** [comment]
Created PR: https://github.com/fabric8io/fabric8-online-docs/pull/377
