### ISSUE TITLE
Che 6 new UI -- screenshot updates

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#252]
Che version 6 will be deployed to OSIO. While the features and the way users interact with the app won't change, the UI will be new. So, screenshots will need to be updated. There are a bunch in the GSG and, I believe, one in the UG.

@mishaone, the Che team offered to migrate your account (so that you'll have access to Che 6) earlier than others. That should give us more time.

**Comment by rkratky** [comment]
Mario: _As soon as Misha opens the codebase UI page her existing workspaces will be migrated (if existing) and new workspaces will be created using Che 6._

**Comment by mishaone** [comment]
Blocked atm due to https://github.com/openshiftio/openshift.io/issues/627 but WIP

**Comment by mishaone** [comment]
Magically unblocked, so will get on this today.

**Comment by mishaone** [comment]
Created and merged first PR: https://github.com/fabric8io/fabric8-online-docs/pull/261

**Comment by mishaone** [comment]
Second PR: https://github.com/fabric8io/fabric8-online-docs/issues/262
