### ISSUE TITLE
GSG and troubleshooting enhancements

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#263]
See https://github.com/openshiftio/openshift.io/issues/2869 for details.

I suggest linking to UG (and Troubleshooting) where suitable.

**Comment by mishaone** [comment]
Issues to address for this issue:
* Second time use for creatin space - add details about what it looks like/what to do if you already create a space.
* Edit log in the pipeline build part - asked question about this, not sure this is a bug
* "4.5. Viewing the build pipeline logs" - what to do if jenkins issue doesn't happen.

**Comment by mishaone** [comment]
Create and merged PR: https://github.com/fabric8io/fabric8-online-docs/pull/272
