### ISSUE TITLE
Drop sections 3.1 and 3.2, clean up API and other suggestions

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#266]
KB:
1) remove all references to fabric8-analytics, the service is openshift.io

2) add a bit more detail around the token, and that it should be kept
private and secure etc

Michal:
1)...drop sections 3.1 and 3.2 completely...
2)Example responses in 4.2.6 and 4.3.6 show quite a lot of data that we don't provide any more. I.e. the fields will be always empty. The API could use some cleanup

Need to clarify with Devs on the final take on this.

**Comment by msrb** [comment]
API cleanup is something that developers need to do first. Only then we can update the docs.

**Comment by msrb** [comment]
Thanks for creating this issue @Preeticp :wink:

**Comment by Preeticp** [comment]
Thanks @msrb can you provide more details on the API cleanup? Will you be creating an issue for the same? Do you think the doc would be blocked by this?

From my side these are the tasks I will take up:
1. Update Supported Ecosystems-remove Pypi, add Swarm
2. Grey out token, add admonition note
3. Drop 3.1, 3.2
4. Update the API response in section 4.2.6 and 4.3.6
Once the cleaned up API is provided, sections 4.2.6 and 4.3.6 can be updated again. Is this alright @msrb?

**Comment by msrb** [comment]
@Preeticp API cleanup was a suggestion from my side, but I am not in charge of that and thus I can't make the call :) @samuzzal-choudhury is your guy :)

I think it would be great to cleanup the API, before people start using it. Without breaking current applications and UI of course - just to remove things that we don't support anymore.

But I have no idea how risky it would be to do such thing now.
