### ISSUE TITLE
Status drop-down going away

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#274]
The status drop-down has been removed. Docs need to be updated to reflect that. AFAICS, this mainly means removing section "3.2. Confirming Che and Jenkins status" from the GSG and all references/links to it.

See https://github.com/openshiftio/openshift.io/issues/3165 for reference (close the issue when this is closed).

**Comment by mishaone** [comment]
Removed the confirming_che_jenkins_status file and images that were only used in it (for tenant status) and removed step for tenant status from cleaning the openshift online module. Builds and validates.

**Comment by mishaone** [comment]
PR created and merged after testing: https://github.com/fabric8io/fabric8-online-docs/pull/279
