### ISSUE TITLE
Che docs for UG

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#275]
@mishaone @Preeticp Do we have anything about Che in the UG? I don't think we do, which seems like a gap. We talk about Che in the GSG, but this part is missing from the UG. I think at least basics should be covered. Something like:

1. Working with _(Using?)_ the Che IDE
1.1 About Eclipse Che
1.2 Creating _(and configuring?)_ a Che workspace _(single-sourced from GSG?)_
1.3 Navigating the Che enviropnment
1.4 Editing code in Che
1.5 Using Git from within Che
1.6  Additional resources

WDYT?

**Comment by mishaone** [comment]
Should be doable, mostly by repurposing the GS Che stuff. If someone will
make an issue for GA and assign it to me, I'll look into it asap.

**Comment by rkratky** [comment]
Closing; continued in #277.
