### ISSUE TITLE
Add troubleshooting item about resetting build info

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#276]
See https://github.com/openshiftio/openshift.io/issues/2807 for details.

Sidenote: we need to track this sort of stuff (i.e. troubleshooting instructions that are only included until a specific issue is fixed in the app) -- lacking a better idea, please, add a comment in the source code alongside the new item (incl. link to relevant os.io issue).

**Comment by mishaone** [comment]
PR: https://github.com/fabric8io/fabric8-online-docs/pull/364
