### ISSUE TITLE
Expand "About Spaces" module in UG

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#28]
Expand on the spaces module. Preeti's comment for context:

> But just wanted to add this note, so that we do not lose track of it, IMHO we need to flesh this topic out more. At the time we had got in whatever little content we could gather. I guess we need to follow up with the Platform team for more information. For instance, the relation of templates with space, which determines the Planner WIs etc.

**Comment by mishaone** [comment]
@Preeticp tagging you for visibility.

**Comment by Preeticp** [comment]
@mishaone @rkratky, #192 will overlap with this issue. I do not remember what we decided to do with this issue in our triaging on monday, but there is no point on working on this now as the experience will change with the new launcher experience.

**Comment by rkratky** [comment]
@Preeticp Is the definition/description of what 'spaces' are going to change? If not, I think this issue is still valid.

**Comment by Preeticp** [comment]
Right @rkratky, sorry, I got confused with the 'Configuring a Codebase' section.

**Comment by mishaone** [comment]
Done in https://github.com/fabric8io/fabric8-online-docs/pull/205
