### ISSUE TITLE
Update configuring your Che-workspace

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#289]
Eivantsov> some Che stuff that isn't required at all i think.. checking git menu first, then configuring project as maven... looks like troubleshooting when things go wrong.. and afaik project import in Che6 workspace is fine.
https://docs.openshift.io/getting-started-guide.html#configuring_your_che_workspace-hello-world the very purpose of having che-starter in place is to configure project in workspace config, so that when the IDE loads the project, it knows what kind of project it is and how to handle it

**Comment by mishaone** [comment]
Created and merged PR after validating: https://github.com/fabric8io/fabric8-online-docs/pull/308
