### ISSUE TITLE
document changes to profile/settings

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#290]
Document changes to the profile and settings options. This requires updates to screenshots, possibly workflows and definitely modules in both docs.

Details: https://github.com/fabric8-ui/fabric8-ui/pull/2711
reported by @joshuawilson

**Comment by mishaone** [comment]
Updating to SEV1. Engineering needs docs for this change before the changes can be pushed to prod, so we need to get this done ASAP. Puting the launcher story on hold after merging the changes I have so far for it and switching to this today.

**Comment by mishaone** [comment]
Created PR: https://github.com/fabric8io/fabric8-online-docs/pull/292

**Comment by mishaone** [comment]
Merged and published in prod-preview docs. Some examples of the bigger changes:

* https://docs.prod-preview.openshift.io/getting-started-guide.html#optional_detailed_views
* https://docs.prod-preview.openshift.io/user-guide.html#optin_in_to_features

@joshuawilson - this should be good to push to prod.

**Comment by joshuawilson** [comment]
thanks

**Comment by joshuawilson** [comment]
has it been pushed to prod yet?

**Comment by mishaone** [comment]
@joshuawilson yes, it is now available on docs.openshift.io as well.

**Comment by joshuawilson** [comment]
ok, thanks
now let's see if I can get the UI to prod
