### ISSUE TITLE
Add Docs for Scrum template

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#293]
This is currently in Prod preview.

**Comment by rkratky** [comment]
@Preeticp Could you please link the related eng/ux issues?

**Comment by Preeticp** [comment]
Discussion docs: https://docs.google.com/presentation/d/18xKQmkf3UKlGoP7qLqUnrIYiflza674n_paUZXKuepA/edit#slide=id.g3758dca8f8_0_53

https://docs.google.com/spreadsheets/d/1iQ3MBitXy5zWAvxWzHQKtXuv5SWs_uUCQvrqngfm5K8/edit?ts=5ab54f17#gid=1844742388

https://github.com/fabric8-services/fabric8-wit/pull/1148#issuecomment-381895791

Currently on prod-preview

**Comment by Preeticp** [comment]
This is in prod now umping severity.

**Comment by Preeticp** [comment]
Fixed via #309
