### ISSUE TITLE
Cross Origin support for infotip JSON file

### ISSUE THREAD

**Issue by sanbornsen** [fabric8io/fabric8-online-docs#296]
Fabric8-ui net is likely to consume the infotip data from [here](https://docs.openshift.io/json/infotips.json), but this api is not cross origin supported. 

Solution: Add respective header to allow all origins.

**Comment by jmelis** [comment]
Relevant: https://enable-cors.org/server_nginx.html

**Comment by jmelis** [comment]
This should be added in the Dockerfiles:

- https://github.com/fabric8io/fabric8-online-docs/blob/master/Dockerfile.deploy
- https://github.com/fabric8io/fabric8-online-docs/blob/master/Dockerfile.deploy.rhel

**Comment by piyush1594** [comment]
Hey,

Maybe this can help Adding a file like this https://github.com/shakyShane/nginx-cors-plus/blob/master/default.conf and then copying this file in your nginx container https://github.com/shakyShane/nginx-cors-plus/blob/master/Dockerfile#L3 to enable cors 

I am not sure but I think this can resolve. Apologies in advance if it does not help I have not tried it.
