### ISSUE TITLE
Creating new space screenshots in GSG

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#307]
From #openshiftio:

A: Am trying to use openshift3 online for first time. Using openshift.io Getting Started Guide. None of the screen shots match what I see on my screens. Am stuck at https://openshift.io/_home witn no place to go.

B: You are looking section 4 here: https://docs.openshift.io/getting-started-guide.html, correct?

A: There is no way to get to providing an application name.  Following instructions in https://docs.openshift.io/getting-started-guide.html takes me back to home screen. Should I reset everything and start over?

C: You can create a new space if you click on the blue + (see the list of recent spaces) or from the top left menu. it looks like the getting started guide should be updated. And also there seem to be some UX issues because creating a new space/app should be intuitive and you don't have to read the guide to do so.

B: If you already have 2 applications created then you should reset to try a new one (or go in and delete the old ones). There is a limit to the resources you can use at once. You can also scale down the pods for any apps that you want to keep.

A: This is probably the case. WIll try resetting/deleting. Thanks

**Comment by mishaone** [comment]
What are the action items here? It's hard to tell exactly what the issue was (more than two pods, OSIO not cooperating, or other?) here. Maybe an initial module in ch 4 that shows the full screen on OSIO and then zooms in on the space instructions? Thoughts, @rkratky?

**Comment by mishaone** [comment]
@rkratky right, thanks. I'm still inclined to add a "this is what your home screen looks like and then zoom in to creating a space after reading the feedback. It seems like a decent idea whether or not it helps (or was intended) in this actual use case and is easy enough to do.

**Comment by mishaone** [comment]
Are we okay with using this issue to track the before we start sort of homepage introduction we discussed?

**Comment by rkratky** [comment]
> Are we okay with using this issue to track the before we start sort of homepage introduction we discussed?

+1

**Comment by mishaone** [comment]
Update: 
```@misha -- I finally got it working, not sure what I did differently to make it happen, maybe used my startup account rather than pro. But it did eventually work on pro too.```

**Comment by mishaone** [comment]
PR: https://github.com/fabric8io/fabric8-online-docs/pull/323

**Comment by mishaone** [comment]
Updated and available here: https://docs.prod-preview.openshift.io/getting-started-guide.html#introduction_to_homescreen

Hopefully this provides some context to start with for users about what they should be seeing when they first log in.

**Comment by mishaone** [comment]
IMO this should be ok to close. Please reopen if more work is required.
