### ISSUE TITLE
Jmelis: I think this is out-dated: https://docs.openshift.io/getting-started-guide.html#changing_quickstart_code-hello-world

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#339]
More context on MM OSIO channel

**Comment by Preeticp** [comment]
From OSIO MM channel: 
@maxandersen I'm going through the quickstart and I noticed something strange. I changed the code in the che workspace, pushed to origin, saw the pipeline rebuild, but the staging url does not show the changes. Is there a way to tell the commit that was used to build the image?

alexey profile image	
alexey
2:36 AM
try again. Most likely the new version didn't start yet

2:37 AM
there was an issue for that. I don't think it's fixed

jmelis profile image	
jmelis
2:37 AM
it's been 15 mins

alexey profile image	
alexey
2:38 AM
tryied refresh?

2:38 AM
in browser

jmelis profile image	
jmelis
2:38 AM
yeah, incognito

2:39 AM
ah, the commit is in the jenkins job of course

2:40 AM
it looks correct

alexey profile image	
alexey
2:41 AM
what's the link? to the app

2:41 AM
and the github repo

toddmancini profile image	
toddmancini
2:43 AM
@jmelis also try a hard refresh in the browser. Ctrl+f5

Or whatever is the right key combo

jmelis profile image	
jmelis
2:44 AM
I think I must be changing code in the wrong place...

https://github.com/jmelis/app-test-1/commit/85df575c7799635aebdb39c92ffd87494f635956

http://app-test-1-jmelisba-stage.8a09.starter-us-east-2.openshiftapps.com/

toddmancini profile image	
toddmancini
2:47 AM
Yes, wrong code change 😁

That booster you used stores the greeting in a confif file

That code you changed doesn't get called 

But you did change an API

http://app-test-1-jmelisba-stage.8a09.starter-us-east-2.openshiftapps.com/api/greeting

jmelis profile image	
jmelis
2:50 AM
it's not the same api as in the main web page?

where is it defined?

toddmancini profile image	
toddmancini
2:51 AM
https://github.com/jmelis/app-test-1/blob/master/app-config.yml

jmelis profile image	
jmelis
2:51 AM
I saw that, but that doesn't include the 'World' default

the only place I saw World was where I changed it

ahhh

it's in the javascript!!!

https://github.com/jmelis/app-test-1/blob/master/src/main/resources/webroot/index.html#L62

ok, sorry for the noise  thanks a lot @toddmancini and @alexey 

toddmancini profile image	
toddmancini
2:53 AM
In the JS

Yeah 

No worries! There is some dead code in there that should be removed. 

jmelis profile image	
jmelis
2:56 AM
Also, I think this is out-dated: https://docs.openshift.io/getting-started-guide.html#changing_quickstart_code-hello-world

toddmancini profile image	
toddmancini
3:05 AM
@rkratky ^^

@jmelis we should confirm that you used the same booster as listed in the getting started guide. We'll make sure all of the instructions are accurate and clear. Thanks for the feedback!

**Comment by jmelis** [comment]
@Preeticp this is what I did:

* In the Choose a mission section, select the Externalized Configuration option.
* In the Choose a runtime section, select Eclipse Vert.x.

Is this what you are asking? I tried with a new app and the code is the same, which does not exactly match the description in the quickstart, in particular the [5.13. Changing the quickstart code](https://docs.openshift.io/getting-started-guide.html#changing_quickstart_code-hello-world) section.

**Comment by Preeticp** [comment]
Thank you @jmelis we will test this and update the instructions accordingly.

**Comment by jmelis** [comment]
As you can see, the following snippet is not found [here](https://github.com/jmelis/app-test-9/blob/master/src/main/java/io/openshift/booster/HttpApplication.java):

```java
protected static final String template = "Hello, %s!";
```

**Comment by jmelis** [comment]
Thanks @Preeticp !

**Comment by Preeticp** [comment]
@misha, today got help in getting our docs build to pass and got all our doc changes so far on Prod. 

I could not get very far on this issue. However, I have reviewed our docs and tested the steps till section 5.13 and I have noted the following changes required:

1.  I can validate what Jmelis mentions here, we no longer have the the string: protected static final String template = "Hello, %s!" in `src > main > Java > io.openshift.booster > HttpApplication.java`.
Also he is right the only place `World` is mentioned is in: https://github.com/jmelis/app-test-1/blob/master/src/main/resources/webroot/index.html#L62 but I dont think we want to make any changes there.
So step 2 and 3 in 5.13 definitely need some changes. 
Can you please check with @ldimaggi and get further input on this and take care of this change, if you know more about this? Do we have any other points of contact for information on this?
I can help with the other changes below once I come online tomorrow, just let me know what you think of some of the suggestions below.
2.  References to 'add to space' on dashboard to start application launcher, needs to be changed to Create an Application
3.  5.3>8b, when I click view new app it takes me to the dashboard, we need to tell user where to go next. Space dashboard has changed no longer shows the Pipelines view, we have screenshots in 5.5 which need to be updated and instructions modified to point user to the Pipelines page.
4.  Section 5.4 could go ahead of 5.8? Seems more relevant to the next actions user will be expected to take, wdyt?
5.  5.9 c step needs to change, we have screenshots for experimental but we talk about internal, also as of now internal no longer exists, how about a link to settings section in user guide?
6.  5.9 second section step, click 'view openshift console'
7.  5.12> No projects explorer now, it is straight away app nameapp-test-1 (master)

**Comment by mishaone** [comment]
Testing this now to find an alternate path. @rkratky - is there some discussion we can do with the quickstarts team regarding them informing us when they change the contents of the quickstarts to make our instructions outdated? I updated the che6 content a while ago and everything worked as it should.

**Comment by mishaone** [comment]
PR: https://github.com/fabric8io/fabric8-online-docs/pull/342

**Comment by mishaone** [comment]
Should be fixed. Asking Robert to push update asap.

**Comment by Preeticp** [comment]
+1 to discussions with Che quickstart team.
The UX team had started to keep us in loop but I am surprised certain key connecting pieces such as change in name of 'add to space>Create an Application' was not conveyed.
In general, all teams need to keep the docs team in loop.

**Comment by mishaone** [comment]
There's really no other way except for us to be constantly testing the docs from beginning to end (which is an obviously wasteful exercise). If something in the UI changes, I'd propose a tag or something equivalent to "docs_impact" in BZ, ideally when the change is visible in prod-preview at least so we can guage the impact for that change and make the appropriate changes.
