### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#34]
The README file contains obsolete instructions:

- get rid of ccutil mentions
- fix mark-up in asciidoctor instructions
- get rid of references to RHDEVDOCS JIRA

 Also, the process for getting docs from preview to prod needs to be documented:

(as per @Preeticp's mail)

1. Fork and clone the openshiftio/saas-openshiftio directory.
2. Replace the 'hash:' value with your commit ID in the f8-docs.yaml and raise a PR for the same.
3. Ask the maintainers to merge the PR.

**Comment by aditya-konarde** [comment]
> (as per @Preeticp's mail)
>Fork and clone the openshiftio/saas-openshiftio directory.
>Replace the 'hash:' value with your commit ID in the f8-docs.yaml and raise a PR for the same.
>Ask the maintainers to merge the PR.

Won't be required once [this PR](https://github.com/openshiftio/saas-openshiftio/pull/342) is merged.

**Comment by rkratky** [comment]
@aditya-konarde, I see https://github.com/openshiftio/saas-openshiftio/pull/342 has been reverted. Does that mean we should follow the above-mentioned process?

**Comment by aditya-konarde** [comment]
@rkratky yes, there are some limitations around using 'master' as the tag, so we should follow the above mentioned process for now. Will send out the details in an email, and we can coordinate to get someone from the docs team added to saas-openshiftio.
