### ISSUE TITLE
Replace UTC time in docs build with how long ago

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#344]
This is just IMO, but it would be a lot more useful if we could say something like "Last Build: X hrs/min ago" instead of the current information, which is UTC.

**Comment by mishaone** [comment]
@rkratky this sounds like it should be up your alley. It's just a suggestion and low priority. can you take ownership for some point in the future or close it?

**Comment by rkratky** [comment]
@mishaone I saw this when you opened it but forgot to respond.

This is nontrivial. It would require some client-side execution of a script (to determine current time when the page is loaded by the user). I understand it would be nice, but I also think it's bit of an overkill for us now.

Would conversion of the time from UTC to, say, GMT be an improvement?

**Comment by mishaone** [comment]
No worries, it was just a suggestion. I thought the work required would not
be complex, like a currenttime value minus buildpublishtime value. If the
work required is non-trivial, we should definitelyclose it since we have
plenty of other higher priority things to work on instead.

**Comment by rkratky** [comment]
Yeah, that's the thing: you can't get 'currenttime' without running some JavaScript when the user loads the page. The code itself isn't complicated, but I'd rather avoid having JS loading unless necessary.
