### ISSUE TITLE
Cover Resources Section in Settings

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#347]

**Comment by mishaone** [comment]
Is this help wanted, @Preeticp? I can take it if it is.

**Comment by Preeticp** [comment]
Please feel free to take it @mishaone. I noticed it before Summit and at the time we had more pressing things to do.

**Comment by mishaone** [comment]
https://github.com/fabric8io/fabric8-online-docs/pull/362
