### ISSUE TITLE
Update the logo on the docs.openshift.io site to use the OpenShift.io logo

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#365]
@mindreeper> Update the logo on the docs.openshift.io site to use the OpenShift.io logo, rather than the Red Hat Developer Program logo.
https://github.com/openshiftio/openshift.io/issues/3611

**Comment by Preeticp** [comment]
The tabs in the browser for our guides do not show the logo as they do for OSIO and the Old GS guide. (the last 2 tabs in the image below) Let me know if this should be a separate issue.
![screenshot from 2018-08-29 14-08-11](https://user-images.githubusercontent.com/16647625/44776393-a1ede780-ab95-11e8-9b37-e87173d5e918.png)

**Comment by rkratky** [comment]
Dupl. of #160.

**Comment by Preeticp** [comment]
Reopening, as the main issue is about updating docs with the OSIO logo instead of the Developer one used currently. The favicon issue I commented on in the previous comment is a duplicate of #160
