### ISSUE TITLE
Remove sections referring to opt-in feature in GS and link to user guide.

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#372]
Planner(5.2.1. Opt-in to beta features) and Optional views(5.9. (Optional) Detailed views).
It diverts the GS flow. Also, this would help planner section focus on the planning part and 5.9 would be merely one step which could be added to the relevant preceding or next module.

**Comment by mishaone** [comment]
I'm not sure redirecting to a different doc to opt into beta features is the way to go. It seems like more of a derailment. @rkratky @Preeticp WDYT

I would say that I think 5.2.2 looks a bit fuller than most of the modules. Perhaps we can trim down on it and reduce the screenshots or make them more targeted? At the moment, it feels like each step has nearly a full screen screenshot. Thoughts?

**Comment by Preeticp** [comment]
> I'm not sure redirecting to a different doc to opt into beta features is the way to go. It seems like more of a derailment. @rkratky @Preeticp WDYT

We discussed covering prod plus one level, which would be Beta level, if we do that, section 5.2.1 would be moot. 
That leaves us with section '5.9 (Optional) Detailed views'. I feel the opt in feature should be covered in a separate section like it is in the User guide: [Changing user preferences](https://docs.openshift.io/user-guide.html#changing_user_preferences), right at the start of the guide. 
We also have the resources section which is relevant to GS but not yet linked to the GS, plugging this assembly in the GS would take care of that too.

>I would say that I think 5.2.2 looks a bit fuller than most of the modules. Perhaps we can trim down on it and reduce the screenshots or make them more targeted?

+1 to reducing screenshots and making them more targeted.

**Comment by Preeticp** [comment]
Closed via #408 and #414
