### ISSUE TITLE
Codebase section in GS needs to be placed where relevant

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#373]
Section '5.7. About codebases' not appropriately positioned in the doc, should come before '5.3. Creating a new project', it should establish context for '5.3' and 'chapter 10' (Importing an existing project from GitHub).

**Comment by mishaone** [comment]
I was actually thinking it may be worth adding all the concepts at the end, as a sort of glossary and linking to them in the text to negate the issue of breaking the flow with concepts . WDYT?
