### ISSUE TITLE
Define terms Codebase, Application and Project clearly in the glossary and update the docs accordingly.

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#380]
Currently the 3 concepts are not clearly delineated, their relationship is not clear and in a lot of places we use Projects and Application as synonyms.

**Comment by mishaone** [comment]
What exactly is the distinction we want to make? It's a quickstart project while we create it and then when we run it, it becomes the application?

**Comment by Preeticp** [comment]
Afaiu, OSIO enables an user to create a new Application by using OSIO provided (vertx, Springboot, etc.) starter codebases(source code) or import an existing codebase the user already has.
Imho, in OSIO, the term 'Project' should be used to cover the entire development project which covers all the services provided by OSIO, right from Planning, deploying, analyzing to testing. 
I know we use 'Projects' in GH, but I feel the OSIO wizard makes a clear statement here in calling what is created by the wizard as an application. The wizard is a quickstart for creating an application using starter codebases and then building on them in Che. I feel we should not refer to them as quickstart projects at all to avoid confusion as we do not use the word project anywhere in the OSIO UI now.

**Comment by Preeticp** [comment]
This has been addressed via PRs addressing Issues #394 #393 as part of the GSG review.
