### ISSUE TITLE
Create docs for the Agile template, existing Scrum template is deprecated

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#382]
https://github.com/fabric8-services/fabric8-wit/pull/2109
This triggers a whole lot of changes in docs
- Replace Scrum docs with docs for Agile template. Looks like a lot of new elements are being added.
- Create space screenshot will be affected as user will not be able to select Scrum
- We will need to add Infotips and Glossary terms for Agile template, not sure how much of an overlap will exist between the scrum and agile templates.

**Comment by Preeticp** [comment]
To Do:
- [ ] Document concept topics/Infotips for the new fields introduced through Agile template
- [ ] Document workflow docs. Comment out or remove scrum related information from UG and glossary.
- [ ] Update Space related info and screenshots where relevant.
- [ ] Evaluate if Getting started docs need to be updated with this information

**Comment by Preeticp** [comment]
PRs for both work flow and concepts have been pushed. Awaiting final confirmation from Dev lead.

**Comment by kwk** [comment]
> PRs for both work flow and concepts have been pushed. Awaiting final confirmation from Dev lead.

@Preeticp can you please link those PRs here?

**Comment by Preeticp** [comment]
@kwk this is the Agile workflow docs PR: https://github.com/fabric8io/fabric8-online-docs/pull/397
and this is the Concepts one to be added into the glossary and the Json script as per the earlier workflow for infotips: https://github.com/fabric8io/fabric8-online-docs/pull/396

I was planning to mention this in today's daily, I also had a discussion with rkratky wrt the infotips living in the Agile.yaml file. As long as its in a Yaml file we should be able to update it for infotips. 

Only thing is the current setup is more friendly to single sourcing the content. For the new setup we will have to create a PR for glossary in the docs repo and a PR for infotips in the Planner repo. But if this is the optimal solution from the user pov, so be it.

**Comment by Preeticp** [comment]
Closed via #396 and #397
