### ISSUE TITLE
update profile page instructions and screenshots

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#384]
The profile page is updated and contains new things. Update screenshots and instructions as necessary in UG and GSG

**Comment by Preeticp** [comment]
Changes in screenshots and instructions were addressed through this PR for all the 3 guides: https://github.com/fabric8io/fabric8-online-docs/pull/379 for issue https://github.com/fabric8io/fabric8-online-docs/issues/378.
This was needed to be done urgently as Joshua had pushed these changes to prod and needed the docs to be updated immediately. fabric8-ui/fabric8-ui#2777
feat(new-profile): new profile overview and update page design implemented #2777

Do you see any further changes necessary in the Guides for this?

**Comment by mishaone** [comment]
Nope, good to close.
