### ISSUE TITLE
GS update & review: ch 5

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#394]
This chapter includes 20 modules. Please review, improve the wording where required and test to ensure it's still up to date.

**Comment by mishaone** [comment]
I think the planning development work part in particular needs to be trimmed down and made specific to the relevant tasks for this example. If you'd like me to look into that one, I'm happy to swap out one of my modules, just to get someone else to look at it.

**Comment by Preeticp** [comment]
Yes I think we agreed on it in our last discussion. How about I take a shot at it and get it reviewed by you and Robert? If you are still not satisfied maybe you can take over the module. Is that alright?

**Comment by mishaone** [comment]
All good. I offered in case you were sick of looking at it and wanted someone else to do it instead. :)

**Comment by Preeticp** [comment]
Got it :)

**Comment by Preeticp** [comment]
1st [PR](https://github.com/fabric8io/fabric8-online-docs/pull/402)

**Comment by mishaone** [comment]
2nd PR: https://github.com/fabric8io/fabric8-online-docs/pull/408

(adding so that this turns up as work done this week for scrum of scrums

**Comment by Preeticp** [comment]
3rd PR: #414

**Comment by Preeticp** [comment]
4th and final PR: #424 
This completes the review and updates for Chpt 5.
