### ISSUE TITLE
Prepare a nicer landing page

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#40]
The landing page (https://docs.prod-preview.openshift.io/) is butt-ugly. It should be improved to not be an embarrassment.

@joshuawilson, could you please advise who to approach for help with this?

**Comment by joshuawilson** [comment]
@rkratky you should talk to @catrobson. Her team does the design work.

**Comment by rkratky** [comment]
Thanks @joshuawilson. Heh, that's what I wanted to do, but I couldn't find Catherine's nick on GH.

@catrobson, is this something you could help with? Would you need anything from us?

**Comment by catrobson** [comment]
@rkratky Sure, we can help with this.  Can you note any requirements you have, and thoughts on what might live here in the longer term so we can design it to handle today as well as any known future needs?

**Comment by rkratky** [comment]
Thanks @catrobson. For now, we just need:

- a decent overall look, pbbly based on os.io
- some clear heading (it's there already but could look better)
- a way to link to the two docs (again, already there)

What we want to include that's not already there:

- link to OSIO itself
- link to this repo and potentially other relevant repos
- link to the RH Developer Program

Considerations for the future (this will need acks from others, but I imagine it could be useful):

- feed from OSIO-tagged StackOverflow questions
- integration of OSIO elements (login, access to profile, status icon)
- links or feed from OSIO YouTube
- ...?

Also, at this point, the page carries its own CSS, which is awful. I suppose some CSS shared with OSIO could be used to minimize loading time.

**Comment by mishaone** [comment]
Adding a few thoughts on the appearance:
The actual rendering of docs looks good to me, but I wonder if we can do something more useful with the white space to the right that's currently not in use. Perhaps something like the OS docs, where they have a navigation menu to the left and the content to the right? https://docs.openshift.com/online/cli_reference/get_started_cli.html

**Comment by rkratky** [comment]
@mishaone, we can most likely generate the TOC to the side, but this issue is only about the landing page. I created issue #46 to track the TOC thing.

**Comment by rkratky** [comment]
@catrobson, could you please provide a status update on this?

Also, I had a chat with @rhoads-zach who's responsible for RHOAR/LOSIO docs (see https://appdev.openshift.io/docs/), and we discussed the possibility of having a unified landing page for all os.io-related docs (pending acks from interested parties). Could you please, look into that as an option when designing the docs.os.io page?

I believe it would make a lot of sense to have a single docs front page from which links could go to content specific to the different solutions (OSIO, LOSIO, RHOAR, ...).

**Comment by muruGanesan** [comment]
Hi @rkratky,
Can you please see the below issue?
https://github.com/fabric8-ui/fabric8-ux/issues/703#issuecomment-352417951

**Comment by rkratky** [comment]
Clkosing. Header & footer work tracked in #219.
