### ISSUE TITLE
Update OpenShift.io Analytics Integration API Guide to reflect all changes and improvements made in the API

### ISSUE THREAD

**Issue by tisnik** [fabric8io/fabric8-online-docs#410]
The following API Guide needs to be updated:
https://docs.openshift.io/analytics-integration-api-guide.html

Issues:
3.2.6. Example response
- the response format, schema, and meaning of values are not described
- some values (`usage_outliers`) are empty so consumers of the API won't know what expect
- special values needs to be described (where to expect `N/A`, -1 etc.]

3.3.6. Example response
- the response format, schema, and meaning of values are not described.

**Comment by Preeticp** [comment]
@tisnik the docs team would need inputs for these parameters from some one in the Analytics team. @miteshvp, @samuzzal-choudhury, what would be the best way to go about this?

**Comment by Preeticp** [comment]
> @miteshvp response on Mattermost: we will scope this ourselves as part of swagger spec.

**Comment by Preeticp** [comment]
@samuzzal-choudhury, @invincibleJai, @siva, As per discussions in today's meeting: https://bluejeans.com/s/fki@A

1. We need to create another doc with the 3 scale integration method for internal and external users
2. The current OSIO cook book remains, except for changes in the cURL and responses that need to be updated.
