### ISSUE TITLE
Thorough review of user guide as a whole

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#417]
The User guide has not undergone a holistic review so far.
We need to split the guide among us and do a thorough review of the same as we are doing for the getting started now.
There are 2 cases where I feel this is relevant:
1. We will need to use parts of it for the smaller Use cases.
2. We need to consider the possibility of using it for Context sensitive help, in case we need to deliver it.

**Comment by rkratky** [comment]
Unassigning myself and Preeti. @mishaone, could you please DPM this and file separate issues (assigned to indiv. writers) for the indiv. review tasks?

**Comment by mishaone** [comment]
I'll do that and close this task (probably after the minimalism session so that we don't need to do this twice).

**Comment by mishaone** [comment]
@Preeticp actually I'm already tracking the minimalism review and subsequent action items in JIRA and will create issues here after that, so this is not really necessary. I would suggest making separate issues for the two additional items lumped in here with the review (breaking into smaller use cases and context sensitive help). We can create the former later after review, the latter I have no idea about and would possibly be best in a separate issue assigned to you or Robert, whoever is most familiar with the context sensitive help requirements?

**Comment by Preeticp** [comment]
@mishaone the idea earlier was to reuse the modules in User guide for context sensitive help too. Since this is still in the back log, I would suggest that when we do the smaller use cases or modifications to the User guide, we bear this in mind. As of now, we could use your review follow up issues. Also we have an issue tracking the smaller use cases we need in addition to existing ones in place: https://github.com/fabric8io/fabric8-online-docs/issues/415

**Comment by Preeticp** [comment]
Reopening this issue. I think a top level review to identify content which can be reused from here for the smaller use cases issue is required. 
I will also check with the team here if we can get it reviewed in one of the minimalism review meetings.

**Comment by Preeticp** [comment]
This Issue mainly needs reordering of modules as follows, based on priority of tasks in OSIO:
1. Space
2. Codebase
3. Pipelines
4. workspaces
5. Analytics
6. Areas and Collaborators (link assigning area and collaborator to planning sections instead of repeating them) *Discuss* with @rkratky reuse of modules in Assembly of Assemblies, which causes repetition of modules within the same guide, kind of goes against minimalism right?
7. WI and Iterations
8. Resources
Created separate issue #436 to take care of Planner modifications. Otherwise most modules are in good shape.

**Comment by Preeticp** [comment]
#438 1st PR takes care of the introductory paragraphs and reorg of modules in UG
