### ISSUE TITLE
Docs page branding should match OSIO branding

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#421]
I noticed the docs landing page (docs.openshift.io) has Red Hat Developer branding instead of OSIO branding. This is low priority since the branding may change in the future but it should reflect whatever the branding is on the openshift.io page (or new URL, as the case may be). Assigning this to Robert since this probably something he can help with.

**Comment by rkratky** [comment]
Duplicates #365 & #219.
