### ISSUE TITLE
Add info on bug reporting and team/author details

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#61]
Both docs (E2E, UG) need some meta info:

- authors + sources
- where to file bugs against the docs
- how to contribute (i.e. link to repo's README)

**Comment by mishaone** [comment]
I've added links to where to file bugs against the docs to the E2E doc (Introductory chapter).

**Comment by rkratky** [comment]
@mishaone Can we close this? I guess we've got enough info in the GSG. Is that true for the UG, too.

**Comment by mishaone** [comment]
LGTM @rkratky . I was just leaving this open to dump the same information about where to file bugs and seek help in the UG as well. I'll just add that now and close this.

**Comment by mishaone** [comment]
Created PR for this: https://github.com/fabric8io/fabric8-online-docs/pull/170

**Comment by rkratky** [comment]
Fixed by #170.
