### ISSUE TITLE
Fix (adapt) PR build pipeline

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#62]
@rawlingsj, could you please take a look at the Jenkinsfile and *fabric8-online-docs-app* you prepared for this repo? We had to change the repo's structure to unify it with RHOAR/LOSIO docs, but that broke the pipeline you set up.

I'd be happy to provide additional information or try to fix it myself if you point me in the right direction.

**Comment by rkratky** [comment]
@kbsingh, in light of today's announcement, could you please suggest who to turn to with this issue?

**Comment by maxandersen** [comment]
@chmouel can you take a look here ?

**Comment by rawlingsj** [comment]
FWIW my understanding was that this project would be built by ci centos and not fabric8 pipelines anymore.  The discussion is here https://github.com/fabric8io/fabric8-online-docs/pull/16

**Comment by maxandersen** [comment]
@rkratky the PR builds seem to still be active on https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8io-auto-rel%2Ffabric8-online-docs/detail/PR-119/1/pipeline and the error there indicates what is needed is to update this line https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8io-auto-rel%2Ffabric8-online-docs/detail/PR-119/1/pipeline to invoke `scripts/build_guides.sh` instead.

**Comment by maxandersen** [comment]
I made a PR attempt at https://github.com/fabric8io/fabric8-online-docs/pull/120 but I kinda expect it to fail as random PR's shouldn't allow change to jenkinsfile.

@rawlingsj whats the "policy"/rules jenkins is setup for around jenkinsfile updates ? who can change them in PR's ?

**Comment by maxandersen** [comment]
> I made a PR attempt at #120 but I kinda expect it to fail as random PR's shouldn't allow change to jenkinsfile.

@rkratky it is more than just the build scripts that changed, also the dockerfile was altered so it will take some more time to adjust it if at make sense at all. 

> @rawlingsj whats the "policy"/rules jenkins is setup for around jenkinsfile updates ? who can change them in PR's ?

I figured out I at least can change it, hopefully because i'm member of the org - but got some questio around that on #120 if you could be so kind to look there.

**Comment by rkratky** [comment]
> @rkratky the PR builds seem to still be active on https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8io-auto-rel%2Ffabric8-online-docs/detail/PR-119/1/pipeline and the error there indicates what is needed is to [...] to invoke scripts/build_guides.sh instead.

@maxandersen, right. I did have a look at that, but since I don't really understand the build logic (and the role of https://github.com/fabric8-apps/fabric8-online-docs-app), I thought a mere change of the command line would not help.

> it is more than just the build scripts that changed, also the dockerfile was altered so it will take some more time to adjust it if at make sense at all.

FWIW, the Dockerfiles are not used at all if only `scripts/build_guides.sh` is run. The containers are only built when the `cico_build_deploy.sh` script is executed.

**Comment by rkratky** [comment]
Fixed by #126.
