### ISSUE TITLE
Generate JSON with [tool|info]tips for Planner

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#63]
Infotips content based on OSIO User Guide Glossary needs to be converted to Markdown and then JSON with the following structure:

```
{
  "tooltips": {
    "id_tooltip_0": { "en_EN": "Some **markdown** text." },
    "id_tooltip_1": { "en_EN": "This can also include linebreaks." }
  },
  "infotips": {
    "id_infotip_0": { "en_EN": "Some **markdown** text." },
    "id_infotip_1": { "en_EN": "This can also include linebreaks." }
  }
}
```
IDs to be generated as UUID.

There will be a separate file for tooltips and infotips, which will be served as:

https://docs.openshift.io/json/infotips.json
https://docs.openshift.io/json/tooltips.json

**Comment by Preeticp** [comment]
Robert this will be part of the G train, so we will need to up the priority on this one.

**Comment by rkratky** [comment]
To close, script needs to be fully automated.

**Comment by rkratky** [comment]
Closing; script (`scripts/export_infotips.sh`) working. Script improvements tracked in #218.
