### ISSUE TITLE
Update outdated terminology

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#71]
Some terms have evolved and need to be updated.

_the user guide and on boarding documentation were based, in part, upon other non-canonical (e.g. the first several revisions of the workshop document) or outdated sources (e.g. the glossary) and, as such, has issues related to the naming of things, the messaging behind certain capabilities, etc. (e. g. OSIO has neither Projects nor Collaboration Spaces, both of which are older, deprecated terms.)_

Use Todd's GSG as reference: https://drive.google.com/file/d/0B84xd3xHpx5cNlRuaC1aM1NsMVk/view

**Comment by Preeticp** [comment]
Review for use of Projects in lieu of Application.

**Comment by rkratky** [comment]
@Preeticp, did you mean Application in lieu of Project?
