### ISSUE TITLE
Fix lowercase i rendering so it doesn't look like a lowercase L

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#72]
I can't see the previews at the moment, but I think they also have this issue.

Currently, for everything that is not marked up, the docs font renders in a way that makes every lowercase i look like a lowercase L. See screenshot for examples of this:

![inotl](https://user-images.githubusercontent.com/926572/33113605-ddd3a24e-cfa4-11e7-92ae-27483d3c9e32.png)

Expected behavior is that the lowercase i should clearly look different from a lowercase L.

**Comment by mishaone** [comment]
Hi @rkratky - not sure if this is in the preview and if it is, if we are the ones who can fix this, but have assigned to you and myself.

**Comment by rkratky** [comment]
@mishaone, do you mean the font that is being used should be changed?

**Comment by mishaone** [comment]
@rkratky, I can see the preview doc today and it looks like it doesn't have the same issue. I guess it's just local, which ideally would be as similar as possible to the final rendering, but we can work around this. It looks like admonitions also render oddly in my local asciidoctor build, but that issue is also not in the preview so all good. Closing this as notabug.
