### ISSUE TITLE
"TODO with modules"?

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#73]
What does this sentence at the end of the e2e guide mean? Can it be removed (or commented out)?

**Comment by mishaone** [comment]
Hi Robert,

That's placeholder text because we need to reuse many of the modules from the earlier sections after making them a bit more generic for use in multiple areas (this is now mostly done).

**Comment by rkratky** [comment]
So, can it be removed?

**Comment by rkratky** [comment]
fixed by #95
