### ISSUE TITLE
Update mark-up based on RH-wide conventions

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#86]
Our mark-up should observe conventions set forth in https://redhat-documentation.github.io/asciidoc-markup-conventions

Some of these changes can be automated, the rest will need to happen manually.

**Comment by Preeticp** [comment]
As per #114 we felt references to GUI elements should be in small case throughout the doc, unless in places where it was part of actionable instructions.
>> unless we are using it in action instructions Eg., 'Click Space' we could use small case for space when we are simply referring to them
>I agree with this. To share the specific example we discussed with Preeti today:

>"open a new space by clicking on Space in the menu" (that's just to illustrate the difference; I hope such sentence won't end up in actual docs ;)

**Comment by rkratky** [comment]
Partially (GUI items styling) fixed by #145. @Preeticp, @mishaone, please, take note -- we should observe this styling from now on. Btw, I may have accidentally changed even elements that should not have been changed. If you come up on such, please, report it.

What remains is mostly links (use `link:`) -- I'll do that using sed.
