### ISSUE TITLE
Unify action headings on gerunds

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#92]
To provide a consistent feel, action headings should all use gerund forms. E.g. consider:

7.13. Changing the quickstart code
7.14. Commit and push changes to GitHub
7.15. Review and publish your changes
7.16. Closing a work item

The middle two headings should be converted to:

7.14. Committing and pushing changes to GitHub
7.15. Reviewing and publishing your changes

**Comment by mishaone** [comment]
@Preeticp are you already doing this in your PRs? If you are, please assign this to yourself. If not, I'll take it and do it when you're done.

**Comment by mishaone** [comment]
I'm working on this now. Fixing up IDs as well while I'm at it.

**Comment by Preeticp** [comment]
Ok thanks, I hope we do not have major merge conflicts.

**Comment by mishaone** [comment]
Hopefully not, @Preeticp. I've just updated module IDs, which should be fine, but I also updated some of the module file names, which might be slightly problematic? Hopefully that can just be automatically resolved.

**Comment by mishaone** [comment]
Created PR https://github.com/fabric8io/fabric8-online-docs/pull/132 which is now merged.
