### ISSUE TITLE
Incognito no longer required

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#98]
......
4. Prerequisites

Browser Requirements:

* Currently, only Google Chrome can be used with OpenShift.io. Additional browsers will be added here as they are tested.

* Ensure that you run OpenShift.io in Chrome’s Incognito Mode or as a Guest user. This is required because troubleshooting or other functions require clearing your browser’s history.
.....

Incognito mode is no longer a prerequisite.

**Comment by mishaone** [comment]
Updated and merged: https://github.com/fabric8io/fabric8-online-docs/pull/111
